name: Update

on:
  repository_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
    steps:
      - uses: actions/checkout@v2

      - name: Get PKGBUILD info from repo
        run: |
          curl -LO https://github.com/ClementTsang/bottom/releases/download/${{ github.event.client_payload.version }}/arch_PKGBUILD.tar.gz
          tar xzvf arch_PKGBUILD.tar.gz
          mv PKGBUILD ./bottom
          rm arch_PKGBUILD.tar.gz
      
      - name: Get binary PKGBUILD info from repo
        run: |
          curl -LO https://github.com/ClementTsang/bottom/releases/download/${{ github.event.client_payload.version }}/arch_PKGBUILD_bin.tar.gz
          tar xzvf arch_PKGBUILD_bin.tar.gz
          mv PKGBUILD ./bottom-bin
          rm arch_PKGBUILD_bin.tar.gz

      - name: Update container
        run: |
          pacman -Syu --noconfirm --needed
          pacman -S base-devel --noconfirm --needed
          pacman -S sudo --noconfirm --needed

      - name: Create a dummy user for makepkg to use, since it cannot be root
        run: |
          useradd aur_test -m
          passwd -d aur_test
          printf 'aur_test ALL=(ALL) ALL\n' | tee -a /etc/sudoers

      - name: Make .SRCINFO for PKGBUILDs
        run: |
          chown aur_test -R bottom
          chown aur_test -R bottom-bin
          cd bottom
          sudo -u aur_test makepkg --printsrcinfo > .SRCINFO
          cd ../bottom-bin
          sudo -u aur_test makepkg --printsrcinfo > .SRCINFO

      - name: Create PR
        uses: peter-evans/create-pull-request@v3.5.0
        with:
          commit-message: "Actions: Update AUR PKGBUILD files to ${{ github.event.client_payload.version }}"
          title: "Automatic AUR PKGBUILD update to ${{ github.event.client_payload.version }}"
          body: "This is an automatic update for the AUR PKGBUILD files in response to a bottom release, version ${{ github.event.client_payload.version }}."
          branch: update_branch
          delete-branch: true